import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Automizer, ISlide } from 'pptx-automizer';
import type { Dataset } from '@schema/chart.js';
import type { RealLayout } from '@schema/layouts/real-layouts.js';
import type { LayoutSlot, LayoutSpec } from '../setup/types.js';
import { MasterError } from './errors.js';
import { MASTER_TEMPLATE_ALIAS } from './load-master.js';
import { fillChartSlot } from './fill-chart-slot.js';
import { fillContentSlot } from './fill-content-slot.js';
import { fillTextSlot } from './fill-text-slot.js';

/**
 * `layout-spec.json` is the read-only shapes ≡ slots contract (D22): per-layout
 * master `sourceSlideIndex` + slot names, generated by the setup scripts.
 * Loaded once per process; never edited here.
 */
let cachedSpec: LayoutSpec | undefined;

function loadLayoutSpec(): LayoutSpec {
  cachedSpec ??= JSON.parse(
    readFileSync(
      join(dirname(fileURLToPath(import.meta.url)), '../setup/layout-spec.json'),
      'utf-8',
    ),
  ) as LayoutSpec;
  return cachedSpec;
}

/**
 * Routes one slot to its kind handler. Each handler module is the seam the
 * later Phase-5 tasks extend (text → T-102, content/image → T-103, chart →
 * T-104); kinds without an implementation throw — never silently skip
 * (ERROR_HANDLING.md).
 */
function fillSlot(
  targetSlide: ISlide,
  layoutId: string,
  slot: LayoutSlot,
  value: unknown,
  datasets?: Record<string, Dataset>,
): void {
  switch (slot.regionKind) {
    case 'title':
    case 'section-title':
    case 'subtitle':
    case 'chart-title':
    case 'source':
      fillTextSlot(targetSlide, layoutId, slot, value);
      return;
    case 'content':
    case 'image':
      fillContentSlot(targetSlide, layoutId, slot, value);
      return;
    case 'chart':
      fillChartSlot(targetSlide, layoutId, slot, value, datasets);
      return;
    case 'footer':
      // Footer band is auto-filled, not LLM-supplied (D22) — handling lands
      // with the wider text/content tasks; explicit until then.
      throw new Error(
        `footer slot "${slot.slotName}" on layout "${layoutId}" is not yet supported in T-101`,
      );
  }
}

/**
 * Fills one slide of a real D22 layout:
 *   1. Look up the layout's `sourceSlideIndex` + `slots` in layout-spec.json.
 *   2. Copy that master slide.
 *   3. Dispatch every spec slot to its region-kind handler with the slide's
 *      value for that slot (`slot.<name>` ↔ fill-plan key `<name>`).
 */
export function fillRealLayout(
  automizer: Automizer,
  slide: RealLayout,
  datasets?: Record<string, Dataset>,
): void {
  const layout = loadLayoutSpec().layouts.find((entry) => entry.layoutId === slide.layoutId);
  if (layout === undefined) {
    throw new MasterError(
      `layout "${slide.layoutId}" is missing from src/setup/layout-spec.json — regenerate the spec from the master (never hand-edit)`,
    );
  }

  const values: Record<string, unknown> = { ...slide };

  automizer.addSlide(MASTER_TEMPLATE_ALIAS, layout.sourceSlideIndex, (targetSlide) => {
    for (const slot of layout.slots) {
      const valueKey = slot.slotName.replace(/^slot\./, '');
      fillSlot(targetSlide, layout.layoutId, slot, values[valueKey], datasets);
    }
  });
}
