/**
 * Reference tests for the Sector Risk Summary Authored block.
 *
 * Copy this file when writing tests for a new Authored block.
 *
 * ## Test layers for Authored blocks (simpler than Standard blocks)
 *
 * 1. Manifest shape — manifest properties are well-formed.
 * 2. Attrs — each field definition has the right structure.
 * 3. Template — the declarative render tree is valid.
 * 4. Runtime (TODO until T-160) — defineAuthoredBlock() produces a working
 *    BlockRegistryRecord once T-160 implements the runtime expansion.
 *
 * Note: unlike Standard blocks, Authored blocks do NOT have a TipTap
 * editor-command test layer — the editor wiring is auto-generated by the
 * runtime (T-160), not hand-coded per block.
 */

import { describe, it, expect } from "vitest";
import {
  defineAuthoredBlock,
  type AuthoredBlockManifest,
  type AttrFieldDef,
  type RenderNode,
} from "../../src/blocks/authored/defineAuthoredBlock";

// ── Shared fixture ──────────────────────────────────────────────────────────

const MANIFEST: AuthoredBlockManifest = {
  slug: "sector-risk-summary",
  title: "Sector Risk Summary",
  paletteLabel: "Sector Risk",
  content: "rich-text",
  attrs: [
    {
      kind: "string",
      fieldId: "sectorName",
      label: "Sector",
      placeholder: "e.g. Energy Storage",
      maxLength: 80,
      defaultValue: "",
    },
    {
      kind: "enum",
      fieldId: "riskLevel",
      label: "Risk level",
      options: [
        { value: "low", label: "Low" },
        { value: "medium", label: "Medium" },
        { value: "high", label: "High" },
      ],
      defaultValue: "medium",
    },
    {
      kind: "enum",
      fieldId: "trend",
      label: "Trend",
      options: [
        { value: "improving", label: "Improving ↑" },
        { value: "stable", label: "Stable →" },
        { value: "deteriorating", label: "Deteriorating ↓" },
      ],
      defaultValue: "stable",
    },
  ],
  template: {
    kind: "column",
    gap: 2,
    children: [
      {
        kind: "box",
        padding: 3,
        background: { $token: "colors.semantic.surfaceBackground" },
        borderRadius: 4,
        children: [
          {
            kind: "row",
            gap: 2,
            align: "space-between",
            children: [
              { kind: "heading", level: 3, text: { $ref: "sectorName" } },
              {
                kind: "row",
                gap: 1,
                children: [
                  {
                    kind: "badge",
                    text: { $ref: "riskLevel" },
                    background: { $token: "colors.semantic.accentSubtle" },
                  },
                  { kind: "badge", text: { $ref: "trend" } },
                ],
              },
            ],
          },
        ],
      },
      { kind: "rich-text-slot" },
    ],
  },
};

// ── Layer 1: Manifest shape ─────────────────────────────────────────────────

describe("sector-risk-summary manifest — shape", () => {
  it("has a kebab-case slug", () => {
    expect(MANIFEST.slug).toMatch(/^[a-z][a-z0-9-]*$/);
  });

  it("has a non-empty title and paletteLabel", () => {
    expect(MANIFEST.title.length).toBeGreaterThan(0);
    expect(MANIFEST.paletteLabel.length).toBeGreaterThan(0);
    expect(MANIFEST.paletteLabel.length).toBeLessThanOrEqual(24);
  });

  it("content is a valid variant", () => {
    expect(["rich-text", "none"]).toContain(MANIFEST.content);
  });

  it("attrs is a non-empty array", () => {
    expect(Array.isArray(MANIFEST.attrs)).toBe(true);
    expect(MANIFEST.attrs.length).toBeGreaterThan(0);
  });

  it("template is a RenderNode object with a known kind", () => {
    const VALID_KINDS: RenderNode["kind"][] = [
      "text", "heading", "box", "row", "column",
      "badge", "rich-text-slot", "for-each",
    ];
    expect(VALID_KINDS).toContain(MANIFEST.template.kind);
  });
});

// ── Layer 2: Attrs ──────────────────────────────────────────────────────────

describe("sector-risk-summary attrs", () => {
  function findAttr(fieldId: string): AttrFieldDef {
    const found = MANIFEST.attrs.find((f) => f.fieldId === fieldId);
    if (found === undefined) throw new Error(`attr '${fieldId}' not found`);
    return found;
  }

  it("sectorName is a string field with maxLength", () => {
    const f = findAttr("sectorName");
    expect(f.kind).toBe("string");
    if (f.kind === "string") {
      expect(f.maxLength).toBeDefined();
      expect(f.maxLength).toBeGreaterThan(0);
    }
  });

  it("riskLevel is an enum field with 3 options", () => {
    const f = findAttr("riskLevel");
    expect(f.kind).toBe("enum");
    if (f.kind === "enum") {
      expect(f.options.length).toBe(3);
      const values = f.options.map((o) => o.value);
      expect(values).toContain("low");
      expect(values).toContain("medium");
      expect(values).toContain("high");
      expect(f.defaultValue).toBe("medium");
    }
  });

  it("trend is an enum field with a defaultValue", () => {
    const f = findAttr("trend");
    expect(f.kind).toBe("enum");
    if (f.kind === "enum") {
      expect(f.defaultValue).toBeDefined();
    }
  });

  it("all fieldIds are unique kebab or camelCase strings", () => {
    const ids = MANIFEST.attrs.map((f) => f.fieldId);
    const unique = new Set(ids);
    expect(unique.size).toBe(ids.length);
  });
});

// ── Layer 3: Template ───────────────────────────────────────────────────────

describe("sector-risk-summary template", () => {
  it("root node is a column", () => {
    expect(MANIFEST.template.kind).toBe("column");
  });

  it("template contains exactly one rich-text-slot", () => {
    function countKind(node: RenderNode, kind: RenderNode["kind"]): number {
      if (node.kind === kind) return 1;
      const children =
        node.kind === "box"    ? node.children :
        node.kind === "row"    ? node.children :
        node.kind === "column" ? node.children :
        node.kind === "for-each" ? [node.item] :
        [];
      return children.reduce((acc, c) => acc + countKind(c, kind), 0);
    }
    expect(countKind(MANIFEST.template, "rich-text-slot")).toBe(1);
  });

  it("every AttrRef $ref points to a declared fieldId", () => {
    const validIds = new Set(MANIFEST.attrs.map((f) => f.fieldId));

    function checkRefs(node: RenderNode): void {
      if (node.kind === "text" && typeof node.value !== "string") {
        expect(validIds).toContain(node.value.$ref);
      }
      if (node.kind === "heading" && typeof node.text !== "string") {
        expect(validIds).toContain(node.text.$ref);
      }
      if (node.kind === "badge" && typeof node.text !== "string") {
        expect(validIds).toContain(node.text.$ref);
      }
      if (node.kind === "for-each") {
        expect(validIds).toContain(node.fieldId);
        checkRefs(node.item);
      }
      const children =
        node.kind === "box"    ? node.children :
        node.kind === "row"    ? node.children :
        node.kind === "column" ? node.children :
        [];
      children.forEach(checkRefs);
    }

    checkRefs(MANIFEST.template);
  });

  it("no node has a function-valued field (data-only constraint, ADR-0013)", () => {
    // The TypeScript type system already enforces this at compile time.
    // This runtime check is a belt-and-suspenders guard for manifests loaded
    // from disk after the AST validator passes.
    function assertNoFunctions(value: unknown, path: string): void {
      if (typeof value === "function") {
        throw new Error(`Function found at path: ${path}`);
      }
      if (value !== null && typeof value === "object") {
        for (const [k, v] of Object.entries(value)) {
          assertNoFunctions(v, `${path}.${k}`);
        }
      }
    }
    expect(() => assertNoFunctions(MANIFEST, "manifest")).not.toThrow();
  });
});

// ── Layer 4: Runtime (T-160 stub) ───────────────────────────────────────────

describe("defineAuthoredBlock factory", () => {
  it("throws with the T-160 stub message (pre-T-160 state)", () => {
    // T-160 replaces this throw with the real runtime expansion.
    // Until then, calling the factory must produce this explicit error.
    expect(() => defineAuthoredBlock(MANIFEST)).toThrow(
      /runtime expansion not yet implemented/,
    );
  });

  it("throws with the slug in the message so errors are identifiable", () => {
    expect(() => defineAuthoredBlock(MANIFEST)).toThrow(
      /slug="sector-risk-summary"/,
    );
  });

  // When T-160 lands, replace the two tests above with:
  //
  // it("returns a BlockRegistryRecord with the right schemaName", () => {
  //   const record = defineAuthoredBlock(MANIFEST);
  //   expect(record.schemaName).toBe(MANIFEST.slug);
  // });
  //
  // it("returns a record with all required BlockRegistryRecord fields", () => {
  //   const record = defineAuthoredBlock(MANIFEST);
  //   expect(typeof record.schema).toBe("object");
  //   expect(typeof record.tiptapNode).toBe("object");
  //   expect(typeof record.renderer).toBe("function");
  //   expect(typeof record.toPm).toBe("function");
  //   expect(typeof record.fromPm).toBe("function");
  // });
});
